[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.147.7"
    HUGO_ENV = "production"

[build.environment]
  HUGO_VERSION = "0.147.7"
